sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: h4sQ1QiNfzHwRnOhd1D+/+VNBHLFDD//u0QNmPROy2Yg0jB2+EbZBLl5mhH9SpYHdoUEfpmJu/Qlr1gcX9Gw1w63sh+hDbxYb+knzNoPGhTFh4TFpXupevVHjDgrOVNl1R3ly/Z28SzZMmrpRwLL+yv6M/Tyu4RXRTW5gp5F1cQpJ3ygR8zKgIaUrb0hJOEjgct/vTNZ6G7TyNP2G7UJNwP/zYfu1jKQXb3JZVdtvud77nDeoYbVI7eKtIVPfWbNpKA89BxyCMIvvHHNcenMsvq0DSNxOL8lgv5vg9QXjYxingla6mpjAHraWOEJHoSviV8C//zIiLtMepXhw6pqT7/42UUk7XQay/oP/QFlkc3hthD0+cKtKHBOECugzwyFqw5swlnS/gLdK/gZn6f9VR05DtiVz9Dz8SrZkLImDx5qXAeY/rZtkZSbxNfUVGmL00Lbx9mYyyyg5bZ8UCZsEU8s+zY/pQgxvEfyRI8uU4eYjRVQ9J8+CcKqhdFJBN3t+viogXR/04orQ87GflPgX6+be0pElui6iFFWd0D31hKdBp6WvZfZbx186yJ7QjP33JrQcuZZYlL1lky0pS8sXMqLCghUQduWDo/DD0HC1/B4b/Nfd4ciPtBOVftucErdik6SeOx4f+CvSM+hpWRhIetDB89ImlXRmwXMtmNi3UU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Guy-Mannering-Or-the-Astrologer-Volume-01_5353
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy